### ISSUE TITLE
SCLo is currently broken for aarch64/ppc64le

### ISSUE THREAD

**Issue by arrfab** [alphacc/centos-release-sclo#3]
The actual .repo files coming from centos-release-scl-rh (and same for other one) are just wrong and still point to /centos/ and baseurl.
It was asked in October to switch all that to mirrorlist instead.
The following works fine : 

--- CentOS-SCLo-scl-rh.repo.orig	2019-03-29 14:11:19.063688286 +0000
+++ CentOS-SCLo-scl-rh.repo	2019-03-29 14:11:55.773858984 +0000
@@ -5,7 +5,7 @@
 
 [centos-sclo-rh]
 name=CentOS-7 - SCLo rh
-baseurl=http://mirror.centos.org/centos/7/sclo/$basearch/rh/
+mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=sclo-rh
 gpgcheck=1
 enabled=1
 gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo

**Comment by vielmetti** [comment]
As reported at https://twitter.com/lemire/status/1111620157712015360

**Comment by arrfab** [comment]
Solved now, through centos-release-scl-rh-2-3.el7.centos.noarch
so "yum install centos-release-scl-rh -y" on aarch64/ppc64le now works as it should.
Closing this ticket
